/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCard: typeof import('./src/components/index/TheCard.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheList: typeof import('./src/components/index/TheList.vue')['default']
    ThePortfolio: typeof import('./src/components/index/ThePortfolio.vue')['default']
    ThePortfolioList: typeof import('./src/components/index/ThePortfolioList.vue')['default']
  }
}
