/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/assets': RouteRecordInfo<'/assets', '/assets', Record<never, never>, Record<never, never>>,
    '/binding/bank': RouteRecordInfo<'/binding/bank', '/binding/bank', Record<never, never>, Record<never, never>>,
    '/binding/usdt': RouteRecordInfo<'/binding/usdt', '/binding/usdt', Record<never, never>, Record<never, never>>,
    '/buy/down/[key]': RouteRecordInfo<'/buy/down/[key]', '/buy/down/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/buy/up/[key]': RouteRecordInfo<'/buy/up/[key]', '/buy/up/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/fluctuation': RouteRecordInfo<'/fluctuation', '/fluctuation', Record<never, never>, Record<never, never>>,
    '/fund': RouteRecordInfo<'/fund', '/fund', Record<never, never>, Record<never, never>>,
    '/grow/current': RouteRecordInfo<'/grow/current', '/grow/current', Record<never, never>, Record<never, never>>,
    '/grow/histroy': RouteRecordInfo<'/grow/histroy', '/grow/histroy', Record<never, never>, Record<never, never>>,
    '/grow/solution': RouteRecordInfo<'/grow/solution', '/grow/solution', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/me': RouteRecordInfo<'/me', '/me', Record<never, never>, Record<never, never>>,
    '/menu/auth': RouteRecordInfo<'/menu/auth', '/menu/auth', Record<never, never>, Record<never, never>>,
    '/menu/avator': RouteRecordInfo<'/menu/avator', '/menu/avator', Record<never, never>, Record<never, never>>,
    '/menu/company': RouteRecordInfo<'/menu/company', '/menu/company', Record<never, never>, Record<never, never>>,
    '/menu/language': RouteRecordInfo<'/menu/language', '/menu/language', Record<never, never>, Record<never, never>>,
    '/menu/message/detail/[key]': RouteRecordInfo<'/menu/message/detail/[key]', '/menu/message/detail/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/menu/message/full': RouteRecordInfo<'/menu/message/full', '/menu/message/full', Record<never, never>, Record<never, never>>,
    '/menu/message/list': RouteRecordInfo<'/menu/message/list', '/menu/message/list', Record<never, never>, Record<never, never>>,
    '/menu/payment': RouteRecordInfo<'/menu/payment', '/menu/payment', Record<never, never>, Record<never, never>>,
    '/menu/recommend/': RouteRecordInfo<'/menu/recommend/', '/menu/recommend', Record<never, never>, Record<never, never>>,
    '/menu/recommend/history': RouteRecordInfo<'/menu/recommend/history', '/menu/recommend/history', Record<never, never>, Record<never, never>>,
    '/menu/secure': RouteRecordInfo<'/menu/secure', '/menu/secure', Record<never, never>, Record<never, never>>,
    '/menu/top-up': RouteRecordInfo<'/menu/top-up', '/menu/top-up', Record<never, never>, Record<never, never>>,
    '/menu/withdraw': RouteRecordInfo<'/menu/withdraw', '/menu/withdraw', Record<never, never>, Record<never, never>>,
    '/order/history': RouteRecordInfo<'/order/history', '/order/history', Record<never, never>, Record<never, never>>,
    '/order/to-hold': RouteRecordInfo<'/order/to-hold', '/order/to-hold', Record<never, never>, Record<never, never>>,
    '/passwrod/login': RouteRecordInfo<'/passwrod/login', '/passwrod/login', Record<never, never>, Record<never, never>>,
    '/passwrod/payment': RouteRecordInfo<'/passwrod/payment', '/passwrod/payment', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/top-up/bank': RouteRecordInfo<'/top-up/bank', '/top-up/bank', Record<never, never>, Record<never, never>>,
    '/top-up/usdt': RouteRecordInfo<'/top-up/usdt', '/top-up/usdt', Record<never, never>, Record<never, never>>,
    '/trading/day/[key]': RouteRecordInfo<'/trading/day/[key]', '/trading/day/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/trading/five-year/[key]': RouteRecordInfo<'/trading/five-year/[key]', '/trading/five-year/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/trading/month/[key]': RouteRecordInfo<'/trading/month/[key]', '/trading/month/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/trading/week/[key]': RouteRecordInfo<'/trading/week/[key]', '/trading/week/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/trading/year/[key]': RouteRecordInfo<'/trading/year/[key]', '/trading/year/:key', { key: ParamValue<true> }, { key: ParamValue<false> }>,
    '/withdraw/balance': RouteRecordInfo<'/withdraw/balance', '/withdraw/balance', Record<never, never>, Record<never, never>>,
    '/YuEBao/transfer-in': RouteRecordInfo<'/YuEBao/transfer-in', '/YuEBao/transfer-in', Record<never, never>, Record<never, never>>,
    '/YuEBao/transfer-out': RouteRecordInfo<'/YuEBao/transfer-out', '/YuEBao/transfer-out', Record<never, never>, Record<never, never>>,
  }
}
